name: My Action

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened,labeled]

jobs:
  myjob:
    runs-on: ubuntu-latest
    name: Test
    if: ${{ github.event.pull_request.labels.*.name,'Test01')
    steps:
     - run: echo "pass"
