name: My Action

on:
  pull_request:
    branches: [master]
    types: [opened, reopened,labeled]

jobs:
  myjob:
    runs-on: ubuntu-latest
    name: Test
    if: ${{ github.event.pull_request.label.name == 'UI' }}
    steps:
     - run: echo "pass"
